# Generated by Django 5.0.4 on 2024-05-26 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('altura', models.FloatField()),
                ('peso', models.FloatField()),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=400)),
                ('tipo_primario', models.CharField(max_length=15)),
                ('tipo_secundario', models.CharField(blank=True, max_length=15, null=True)),
                ('hp', models.IntegerField()),
                ('ataque', models.IntegerField()),
                ('defesa', models.IntegerField()),
                ('sp_ataque', models.IntegerField()),
                ('sp_defesa', models.IntegerField()),
                ('velocidade', models.IntegerField()),
                ('stats_total', models.IntegerField()),
                ('imagem', models.CharField(max_length=50)),
                ('estagio_um', models.CharField(max_length=50)),
                ('estagio_dois', models.CharField(max_length=50)),
                ('estagio_tres', models.CharField(max_length=50)),
            ],
        ),
    ]
