# Generated by Django 5.0.4 on 2024-05-27 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_alter_pokemon_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='imagem_index',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
