# Generated by Django 5.0.4 on 2024-05-28 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_pokemon_imagem_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='descricao',
            field=models.TextField(max_length=800),
        ),
    ]
