# Generated by Django 5.0.4 on 2024-05-28 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0004_alter_pokemon_descricao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='estagio_dois',
            new_name='estagio_dois_img',
        ),
        migrations.RenameField(
            model_name='pokemon',
            old_name='estagio_tres',
            new_name='estagio_dois_nome',
        ),
        migrations.RenameField(
            model_name='pokemon',
            old_name='estagio_um',
            new_name='estagio_tres_img',
        ),
        migrations.RenameField(
            model_name='pokemon',
            old_name='imagem_index',
            new_name='estagio_tres_nome',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='estagio_um_img',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pokemon',
            name='estagio_um_nome',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pokemon',
            name='imagem_index_img',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
