# Generated by Django 5.0.4 on 2024-05-28 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0005_rename_estagio_dois_pokemon_estagio_dois_img_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='imagem_index_img',
            new_name='imagem_index',
        ),
    ]
