# Generated by Django 5.0.4 on 2024-05-28 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0006_rename_imagem_index_img_pokemon_imagem_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='tipo_primario',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('FIRE', 'Fire'), ('WATER', 'Water'), ('ELECTRIC', 'Electric'), ('GRASS', 'Grass'), ('ICE', 'Ice'), ('FIGHTING', 'Fighting'), ('POISON', 'Poison'), ('GROUND', 'Ground'), ('FLYING', 'Flying'), ('PSYCHIC', 'Psychic'), ('BUG', 'Bug'), ('ROCK', 'Rock'), ('GHOST', 'Ghost'), ('DRAGON', 'Dragon'), ('DARK', 'Dark'), ('STEEL', 'Steel'), ('FAIRY', 'Fairy')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='tipo_secundario',
            field=models.CharField(blank=True, choices=[('NORMAL', 'Normal'), ('FIRE', 'Fire'), ('WATER', 'Water'), ('ELECTRIC', 'Electric'), ('GRASS', 'Grass'), ('ICE', 'Ice'), ('FIGHTING', 'Fighting'), ('POISON', 'Poison'), ('GROUND', 'Ground'), ('FLYING', 'Flying'), ('PSYCHIC', 'Psychic'), ('BUG', 'Bug'), ('ROCK', 'Rock'), ('GHOST', 'Ghost'), ('DRAGON', 'Dragon'), ('DARK', 'Dark'), ('STEEL', 'Steel'), ('FAIRY', 'Fairy')], default='', max_length=20, null=True),
        ),
    ]
